project:
  type: website
  output-dir: _project

# Metadata shared by all documents
date: 2025-06-19
date-format: long
date-modified: last-modified
copyright: BioDT and the UK Centre for Ecology & Hydrology, 2025
license: CC BY
bibliography: references.bib

# Format config shared by all documents
number-sections: true
number-depth: 4
tbl-cap-location: bottom
toc: true
toc-depth: 4
format:
  html:
    code-annotations: hover
    code-overflow: wrap
    embed-resources: true
    highlight-style: github
    html-math-method: mathjax
    repo-actions: source
    toc-location: right
  #pdf:
    #colorlinks: true
    #documentclass: scrartcl
    #toccolor: blue
    #linkcolor: purple

# Website config
website:
  title: The BioDT Recreational Potential Model for Scotland
  navbar:
    left:
      - href: summary.qmd
        text: Summary
      - href: tech_supp.qmd
        text: Technical Supplement
      - href: dev_report.qmd
        text: Developers' Report
      - href: example.qmd
        text: Worked Example
    tools:
      - text: R Package
        icon: github
        href: "https://github.com/BioDT/uc-ces-recreation"
      - text: Data
        icon: database
      - text: Page Source
        icon: git
        href: "https://github.com/BioDT/ces-recreation-reports"

  announcement:
    content: "This site is a **work in progress** and all reports should be considered **drafts**! "
    dismissable: false
    icon: exclamation-circle
    position: above-navbar
    type: danger

# Re-compute only when source changes
execute:
  freeze: auto

# Source author and citation info from these files
metadata-files:
  - authors.yml
  - citation.yml
