project:
  type: website
  output-dir: _site

# Metadata shared by all documents
date: 2025-06-24
date-format: long
date-modified: 2025-07-01
copyright: BioDT and the UK Centre for Ecology & Hydrology, 2025
license: CC BY
bibliography: references.bib
csl: apa.csl

# Format config shared by all documents
number-sections: true
number-depth: 4
tbl-cap-location: bottom
toc: true
toc-depth: 4
format:
  html:
    code-annotations: hover
    code-overflow: wrap
    embed-resources: true
    highlight-style: github
    html-math-method: mathjax
    repo-actions: source
    toc-location: right
    theme:
      light: flatly
      dark: darkly

# Website config
website:
  title: The BioDT Recreational Potential Model for Scotland

  navbar:
    logo: /logos/biodt_circle.png
    left:
      - href: summary.qmd
        text: Summary
      - href: tech_supp.qmd
        text: Technical Supplement
      - href: dev_report.qmd
        text: Developers' Report
      - href: example.qmd
        text: Worked Example
    right:
      - icon: github
        href: "https://github.com/BioDT/ces-recreation-reports"
        target: _blank
      - text: |
          {{< iconify simple-icons:zenodo size=huge >}}
        aria-label: Zenodo
        href: "https://doi.org/10.5281/zenodo.15715070"
        target: _blank

  favicon: /logos/biodt_circle.png
  site-url: https://biodt.github.io/ces-recreation-reports
  repo-url: https://github.com/BioDT/ces-recreation-reports
  
  page-footer:
    left: |
      [![](/logos/biodt.svg){fig-alt="BioDT" width=220px}](https://biodt.eu)
    right: |
      [![](/logos/ukceh.svg){fig-alt="UKCEH" width=250px}](https://www.ceh.ac.uk)

# Re-compute only when source changes
execute:
  freeze: auto

# Source author and citation info from these files
metadata-files:
  - authors.yml
  - citation.yml
