project:
  type: website
  output-dir: _project

# Shared config for all documents

# Metadata
citation:
  author: Joe Marsh Rossney
  title: The BioDT Recreational Potential Model
doi: to-do
#copyright: UK Centre for Ecology & Hydrology, 2025
license: CC BY

bibliography: references.bib
number-sections: true
number-depth: 3
toc: true
toc-depth: 3

format:
  html:
    embed-resources: true
    toc-location: right
    code-overflow: wrap
    highlight-style: github
    html-math-method: mathjax
    code-annotations: hover

  #pdf:
    #colorlinks: true
    #documentclass: scrartcl
    #toccolor: blue
    #linkcolor: purple

# Website config
website:
  title: The BioDT Recreational Potential Model
  navbar:
    left:
      - href: summary.qmd
        text: Summary
      - href: tech_supp.qmd
        text: Technical Supplement
      - href: dev_report.qmd
        text: Developers' Report
      - href: demo.qmd
        text: Code Demo
    tools:
      - text: R Package
        icon: github
        href: "https://github.com/BioDT/uc-ces-recreation"
      - text: Data
        icon: database
      - text: Page Source
        icon: git
        href: "https://github.com/BioDT/ces-recreation-reports"

  page-footer: 
    right: "© Footer"
    border: false
    background: light

# Re-compute only when source changes
execute:
  freeze: auto
