project:
  type: website
  output-dir: _project

# Shared config for all documents

# Metadata in CSL format
# See https://docs.citationstyles.org/en/stable/specification.html
citation:
  id: ukceh2025
  author: 
    - Joe Marsh Rossney
    - Maddalena Tigli
    - Chris Andrews
    - Jan Dick
    - Simon Rolph
  title: The BioDT Recreational Potential Model
  issued: 2025-06
  abstract: |
    These documents describe the BioDT Recreational Potential model at the close of the BioDT project in 2025. Something something.
doi: to-do
license: CC BY
copyright: UK Centre for Ecology & Hydrology, 2025

bibliography: references.bib
number-sections: true
number-depth: 3
toc: true
toc-depth: 3

format:
  html:
    embed-resources: true
    toc-location: right
    code-overflow: wrap
    highlight-style: github
    html-math-method: mathjax
    code-annotations: hover

  #pdf:
    #colorlinks: true
    #documentclass: scrartcl
    #toccolor: blue
    #linkcolor: purple

# Website config
website:
  title: The BioDT Recreational Potential Model
  navbar:
    left:
      - href: summary.qmd
        text: Summary
      - href: tech_supp.qmd
        text: Technical Supplement
      - href: dev_report.qmd
        text: Developers' Report
      - href: demo.qmd
        text: Code Demo
    tools:
      - text: R Package
        icon: github
        href: "https://github.com/BioDT/uc-ces-recreation"
      - text: Data
        icon: database
      - text: Page Source
        icon: git
        href: "https://github.com/BioDT/ces-recreation-reports"

  page-footer: 
    right: "© Footer"
    border: false
    background: light

# Re-compute only when source changes
execute:
  freeze: auto
