project:
  type: website
  output-dir: _project

# Metadata shared by all documents
date: 2025-06-19
date-format: long
date-modified: last-modified
copyright: UK Centre for Ecology & Hydrology, 2025
license: CC BY
bibliography: references.bib

# Format config shared by all documents
number-sections: true
number-depth: 3
tbl-cap-location: bottom
toc: true
toc-depth: 3
format:
  html:
    embed-resources: true
    toc-location: right
    code-overflow: wrap
    highlight-style: github
    html-math-method: mathjax
    code-annotations: hover
  #pdf:
    #colorlinks: true
    #documentclass: scrartcl
    #toccolor: blue
    #linkcolor: purple

# Website config
website:
  title: The BioDT Recreational Potential Model
  navbar:
    left:
      - href: summary.qmd
        text: Summary
      - href: tech_supp.qmd
        text: Technical Supplement
      - href: dev_report.qmd
        text: Developers' Report
      - href: example.qmd
        text: Worked Example
    tools:
      - text: R Package
        icon: github
        href: "https://github.com/BioDT/uc-ces-recreation"
      - text: Data
        icon: database
      - text: Page Source
        icon: git
        href: "https://github.com/BioDT/ces-recreation-reports"

# Re-compute only when source changes
execute:
  freeze: auto

# Source author and citation info from these files
metadata-files:
  - authors.yml
  - citation.yml
