---
title: The BioDT Recreational Potential Model
authors:
  - name: Joe Marsh Rossney
    orcid: 0000-0002-8082-8566
    affiliation: UK Centre for Ecology & Hydrology
  - name: Maddalena Tigli
    orcid: 0000-0001-8083-0589
  - name: Christopher Andrews
  - name: Jan Dick
  - name: Simon Rolph

date: today
date-format: long
abstract: >
  These documents collectively describe the xyz.

toc: false
number-sections: false

nocite: |
  @Dick2025
---

### Contents

The [Summary](summary.html) provides an overview of the model ...

The [Technical Supplement](tech_supp.html) covers technical details about the BioDT Recreational Potential model (LINK TO SPECIFIC RELEASE). This includes a mathematical description of the model and aspects of the code. This document would be useful for someone aiming to understand the full process, starting from the download of ‘raw’ datasets, and following through all the way to the final RP calculation.

The [Developers' Report](dev_report.html) provides a high-level, chronological overview of development work carried out between November 2024 and June 2025. The intention is to provide some context and explanation for posterity. We also make several recommendations for further development work. It would be useful for someone intending to continue development of the RP model.

The [Code Demonstration](demo.html) ...

### Code and data

Code for the Recreational Potential model is available as an R Package hosted on GitHub at https://github.com/BioDT/uc-ces-recreation.

The model requires some input data, which has been deposited on Zenodo **HERE**.

**To do:** specific version of code on Zenodo?

### Associated publications

:::{#refs}
:::

- SPEAK paper
- BioDT paper
- Simon's paper
- Code/data DOI